version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your_secret_key
      - FLASK_APP=secret_santa_app
      - FLASK_ENV=production
    volumes:
      - .:/app
    restart: always
