version: '3'

services:
  web:
    build: .
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

